config/routes.rb
Rails.application.routes.draw do
  get 'analytics/index'
  resources :executions do
    member do
      post 'action'
    end
  end
  resources :environments
  resources :scripts do
    member do
      post 'action'
    end
  end
 
  devise_for :users
  root 'home#index'
  get 'home/index'
end

app/models/script.rb
class Script < ApplicationRecord
  has_paper_trail only: [:aasm_state]
  before_update :edit, unless: :aasm_state_changed?
  has_many :executions, dependent: :destroy
  validates :title, presence: true
  validates :path_to_application, presence: true
  validates :command, presence: true
  USER_EVENTS = %i[approve]

  include AASM

  aasm do
    state :new, initial: true
    state :untested
    state :tested
    state :deployed

    event :approve do
      transitions to: :tested
    end

    event :edit do
      transitions to: :untested
    end

    event :deploy do
      transitions from: :tested, to: :deployed
    end

    event :reset do
      transitions to: :new
    end
  end

  def file_name
    "#{id}_#{title.underscore.split(' ').join('_')}"
  end
end

app/controllers/scripts_controller.rb
class ScriptsController < ApplicationController
  before_action :set_script, only: [:show, :edit, :update, :destroy, :action]
  # POST /scripts/1/<actiion>
  def action
    authorize(@script)
    @script.send(script_params.dig(:action) + '!')
    respond_to do |format|
      format.html { redirect_to scripts_url, notice: "Successfully ran action '#{script_params.dig(:action)}' on script." }
      format.json { head :no_content }
    end
  end


  # GET /scripts
  # GET /scripts.json
  def index
    authorize(Script)
    @scripts = Script.order(started_at: :desc).page params[:page]
  end

  # GET /scripts/1
  # GET /scripts/1.json
  def show
  end

  # GET /scripts/new
  def new
    @script = Script.new
  end

  # GET /scripts/1/edit
  def edit
  end

  # POST /scripts
  # POST /scripts.json
  def create
    @script = Script.new(script_params)

    respond_to do |format|
      if @script.save
        format.html { redirect_to @script, notice: 'Script was successfully created.' }
        format.json { render :show, status: :created, location: @script }
      else
        format.html { render :new }
        format.json { render json: @script.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scripts/1
  # PATCH/PUT /scripts/1.json
  def update
    respond_to do |format|
      if @script.update(script_params)
        format.html { redirect_to @script, notice: 'Script was successfully updated.' }
        format.json { render :show, status: :ok, location: @script }
      else
        format.html { render :edit }
        format.json { render json: @script.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scripts/1
  # DELETE /scripts/1.json
  def destroy
    @script.destroy
    respond_to do |format|
      format.html { redirect_to scripts_url, notice: 'Script was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_script
    @script = Script.find(params[:id])
    authorize(@script)
  end

  # Only allow a list of trusted parameters through.
  def script_params
    params.require(:script).permit(:title, :code, :aasm_state, :path_to_application, :command, :action)
  end
end

app/helpers/scripts_helper.rb
module ScriptsHelper
end

app/views/scripts/_form.html.erb
<%= form_with(model: script, local: true) do |form| %>
  <% if script.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(script.errors.count, "error") %> prohibited this script from being saved:</h2>

      <ul>
        <% script.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.text_field :title, placeholder: "Title", class: "block w-full p-3 mb-4 border rounded border-grey-light", title:"title" %> 

  <%= form.text_field :path_to_application, placeholder: "Application path", class: "block w-full p-3 mb-4 border rounded border-grey-light", title:"application path" %> 

  <%= form.text_field :command, placeholder: "Command", class: "block w-full p-3 mb-4 border rounded border-grey-light", title:"command" %> 

  <div class="mb-5" title="code">
    <div data-controller="codemirror" class="h-auto">
      <%= form.text_area :code, {'data-target':'codemirror.code' } %>
    </div>
  </div>

  <hr class="my-5">

  <div class="flex justify-around actions">
    <%= form.submit class: "py-3 text-center mr-5 text-gray-100 bg-green-400 rounded w-full hover:bg-green-600 focus:outline-none"  %>
    <%= link_to 'Cancel', scripts_path, class: "ml-5 px-4 py-3 text-center text-white bg-gray-600 rounded w-full hover:bg-gray-800" %>
  </div>
<% end %>

app/views/scripts/edit.html.erb
<div class="flex flex-col bg-grey-lighter">
  <div class="container w-full px-2 mx-auto lg:w-1/2">
    <div class="w-full px-6 py-8 text-black bg-white rounded shadow-md">
      <h1 class="mb-8 text-3xl text-center text-gray-600">Editing Script</h1>

      <%= render 'form', script: @script %>

    </div>
  </div>
</div>

app/views/scripts/index.html.erb
<div class="container max-w-5xl p-5 mx-auto bg-white shadow rounded-md">
  <h1 class="mb-8 text-3xl text-center">Scripts</h1>

  <table class="w-full">
    <thead>
      <tr>
        <th>Title</th>
        <th>Application</th>
        <th>Command</th>
        <th>State</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @scripts.each do |script| %>
        <tr>
          <td><%= script.title %></td>
          <td><%= script.path_to_application.split('/').last %></td>
          <td><%= script.command.split('/').last  %></td>
          <td><%= script.aasm_state %></td>
          <td><%= link_to 'show', script, class: "rounded px-2 text-gray-800 bg-gray-400 hover:bg-gray-500 cursor-pointer text-center"  %></td>
          <td><%= link_to 'edit', edit_script_path(script), class: "rounded px-2 text-gray-800 bg-gray-400 hover:bg-gray-500 cursor-pointer text-center"  %></td>
          <td><%= link_to 'destroy', script, method: :delete, data: { confirm: 'Are you sure?' }, class: "rounded px-2 text-red-400 hover:bg-gray-400 cursor-pointer bg-gray-400"  %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="float-right mx-5 my-2 overflow-auto text-gray-600">
    <%= paginate @scripts%>
  </div>

  <hr class="my-5">

  <%= link_to 'New Script', new_script_path, class: "px-4 py-3 text-center text-white bg-green-400 rounded w-full hover:bg-green-600" %>
</div>

app/views/scripts/new.html.erb
<div class="flex flex-col min-h-screen bg-grey-lighter">
  <div class="container w-full px-2 mx-auto lg:w-1/3">
    <div class="w-full px-6 py-8 text-black bg-white rounded shadow-md">
      <h1 class="mb-8 text-3xl text-center">New Script</h1>

      <%= render 'form', script: @script %>

    </div>
  </div>
</div>

app/views/scripts/show.html.erb
<div class="flex flex-col bg-grey-lighter">
  <div class="container w-full px-2 mx-auto lg:w-1/2">
    <div class="w-full px-6 py-8 text-black bg-white rounded shadow-md">
      <h1 class="mb-2 text-3xl text-center text-gray-600">Script: <%= @script.title %></h1>
      <div class="flex justify-center mb-5">
        <table class="border border-separate rounded">
          <tr>
            <td class="p-2">Actions:</td>
            <% (Script::USER_EVENTS & @script.aasm.events(permitted: true).map(&:name)).each do |transition| %>
              <td class="p-2">
                <%= button_to transition, action_script_path(@script), {params: { script: {action: transition} }, data: { confirm: "Are you sure?" }, class: "rounded px-2 text-gray-600 hover:bg-gray-400 cursor-pointer"} %>
              </td>
            <% end %>
            <td class="p-2 border-l">
              State: 
              <%= @script.aasm_state.titleize %>
            </td>
          </tr>
        </table>
      </div>

      <%= form_with(model: @script, local: true) do |form| %>
        <%= form.text_field :path_to_application, disabled: true, placeholder: "Application path", class: "block w-full p-3 mb-4 border rounded border-grey-light"%> 
        <%= form.text_field :command, disabled: true, placeholder: "Command", class: "block w-full p-3 mb-4 border rounded border-grey-light"%> 

        <div class="mb-5">
          <div data-controller="codemirror" class="h-auto">
            <%= form.text_area :code, {'data-target':'codemirror.code' } %>
          </div>
        </div>
        <hr class="my-5">
        <%= link_to 'Request Execution', scripts_path, class: "px-4 py-3 text-center text-white bg-gray-600 rounded w-full hover:bg-gray-800"  %>
        <%= link_to 'Back', scripts_path, class: "px-4 py-3 text-center text-white bg-gray-600 rounded w-full hover:bg-gray-800"  %>
      <% end %>
    </div>
  </div>
</div>