config/routes.rb
Rails.application.routes.draw do
  get 'analytics/index'
  resources :executions do
    member do
      post 'action'
    end
  end
  resources :environments
  resources :scripts do
    member do
      post 'action'
    end
  end
 
  devise_for :users
  root 'home#index'
  get 'home/index'
end

app/models/execution.rb
class Execution < ApplicationRecord
  include CableReady::Broadcaster
  include AASM

  has_paper_trail only: [:aasm_state]
  belongs_to :user
  belongs_to :environment
  belongs_to :script
  has_many :execution_plans
  USER_EVENTS = %i[approve reset].freeze

  after_update do
    cable_ready['card'].morph(
      selector: '#' + ActionView::RecordIdentifier.dom_id(self),
      html: ApplicationController.render(self)
    )
    cable_ready.broadcast
  end

  aasm do
    before_all_events :before_all_events
    state :new, initial: true
    state :approved, after_enter: :schedule_job
    state :setup, after_enter: :reset_all
    state :disapproved
    state :expired
    state :running
    state :succeeded
    state :failed

    event :reset do
      transitions to: :setup
    end

    event :approve do
      transitions from: :new, to: :expired, if: :expired?
      transitions from: :new, to: :approved
      transitions from: :setup, to: :expired, if: :expired?
      transitions from: :setup, to: :approved
    end

    event :disapprove do
      transitions from: :new, to: :disapproved
      transitions from: :setup, to: :disapproved
    end

    event :expire do
      transitions from: :new, to: :expired
      transitions from: :setup, to: :expired
    end

    event :start do
      transitions from: :approved, to: :running
    end

    event :finish do
      transitions from: :running, to: :succeeded, if: :exit_code_is_zero?
      transitions from: :running, to: :failed
    end
  end

  def duration
    return nil if finished_at.nil?

    (finished_at - started_at).seconds
  end

  def expired?
    return false if started_at.blank?

    started_at.past?
  end

  def schedule_job
    if started_at.blank?
      ExecuteJob.perform_later(self)
    else
      ExecuteJob.set(wait_until: started_at).perform_later(self)
    end
  end

  def exit_code_is_zero?
    exit_code.to_i.zero?
  end

  def reset_all
    update(started_at: nil, finished_at: nil, stdout_data: nil, stderr_data: nil)
  end

  def before_all_events
    self.paper_trail_event = aasm.current_event
  end
end

app/controllers/executions_controller.rb
class ExecutionsController < ApplicationController
  before_action :set_execution, only: [:show, :edit, :update, :destroy, :action]
  # POST /executions/1/execute
  def action
    @execution.send(execution_params.dig(:action) + '!')
    respond_to do |format|
      format.html { redirect_to execution_url(@execution), notice: "Successfully ran action '#{execution_params.dig(:action)}' on execution." }
      format.json { head :no_content }
    end
  end

  # GET /executions
  # GET /executions.json
  def index
    authorize Execution
    @executions = Execution.includes(:user, :environment, :script).order(started_at: :desc).page params[:page]
  end

  # GET /executions/1
  # GET /executions/1.json
  def show
  end

  # GET /executions/new
  def new
    @execution = Execution.new(user: current_user)
  end

  # GET /executions/1/edit
  def edit
  end

  # POST /executions
  # POST /executions.json
  def create
    @execution = Execution.new(execution_params)
    @execution.user = current_user

    respond_to do |format|
      if @execution.save
        format.html { redirect_to @execution, notice: 'Execution was successfully created.' }
        format.json { render :show, status: :created, location: @execution }
      else
        format.html { render :new }
        format.json { render json: @execution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /executions/1
  # PATCH/PUT /executions/1.json
  def update
    respond_to do |format|
      if @execution.update(execution_params)
        format.html { redirect_to @execution, notice: 'Execution was successfully updated.' }
        format.json { render :show, status: :ok, location: @execution }
      else
        format.html { render :edit }
        format.json { render json: @execution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /executions/1
  # DELETE /executions/1.json
  def destroy
    @execution.destroy
    respond_to do |format|
      format.html { redirect_to executions_url, notice: 'Execution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_execution
      @execution = Execution.find(params[:id])
      authorize(@execution)
    end

    # Only allow a list of trusted parameters through.
    def execution_params
      params.require(:execution).permit(:aasm_state, :started_at, :finished_at, :input, :output, :user_id, :environment_id, :script_id, :action)
    end
end

app/helpers/executions_helper.rb
module ExecutionsHelper
end

app/views/executions/_execution.html.erb
<div class="container max-w-3xl p-5 mx-auto bg-white shadow rounded-md" id="<%= dom_id(execution) %>">
  <h1 class="text-3xl text-center"> Execution </h1>
  <div class="flex justify-center mb-5">
    <table class="border border-separate rounded">
    <tr>
    <td class="p-2">Actions:</td>
    <% (Execution::USER_EVENTS & execution.aasm.events(permitted: true).map(&:name)).each do |transition| %>
      <td class="p-2">
        <%= button_to transition, action_execution_path(execution), {params: { execution: {action: transition} }, data: { confirm: "Are you sure?" }, class: "rounded px-2 text-gray-600 hover:bg-gray-400 cursor-pointer"} %>
      </td>
    <% end %>
      <td class="p-2 border-l">
        State: 
        <%= execution.aasm_state.titleize %>
      </td>
    </tr>
    </table>
  </div>

  <p>
    <strong>User:</strong>
    <%= execution.user.email %>
  </p>

  <p>
    <strong>Environment:</strong>
    <%= execution.environment.name %>
  </p>


  <p title=<%= execution.started_at.to_s.split(' ').join('_') if execution.started_at.present? %>>
    <% if execution.started_at && !execution.started_at.past? %>
      <strong>Will Start:</strong> in <%= time_ago_in_words(execution.started_at) %>
    <% else %>
      <strong>Started:</strong> <%= time_ago_in_words(execution.started_at) + ' ago' if execution.started_at.present? %>
    <% end %>
  </p>

  <p title=<%= execution.finished_at.to_s.split(' ').join('_') if execution.finished_at.present? %>>
    <strong>Finished:</strong>
      <%= time_ago_in_words(execution.finished_at) + ' ago' if execution.finished_at.present? %>
    </td>
  </p>

  <p>
    <strong>Duration:</strong>
    <% if execution.finished_at.present? && execution.started_at.present? %>
      <%= distance_of_time_in_words(execution.finished_at, execution.started_at) %>
    <% end %>
  </p>

  <p>
    <strong>Script:</strong>
    <%= link_to execution.script.title, script_path(execution.script) %>
  </p>

  <p>
    <strong>Input:</strong>
    <br> <%= text_area_tag 'input', execution.input, disabled: true %>
  </p>

  <p>
    <strong>Output:</strong>
    <br>
    <%= text_area_tag 'output', execution.stdout_data, disabled: true  %>
  </p>

  <p>
    <strong>Errors:</strong>
    <br>
    <%= text_area_tag 'errors', execution.stderr_data, disabled: true  %>
  </p>
  <hr class="my-5">
  <%= link_to 'Back', executions_path, class: "px-4 py-3 text-center text-white bg-gray-600 rounded w-full hover:bg-gray-800" %>
</div>

app/views/executions/_form.html.erb
<%= form_with(model: execution, local: true) do |form| %>
  <% if execution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(execution.errors.count, "error") %> prohibited this execution from being saved:</h2>

      <ul>
        <% execution.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.text_field :started_at, placeholder: "Start at", class: "block w-full p-3 mb-4 border rounded border-grey-light", title:"start at", data: {controller: "flatpickr", target: "flatpickr.self"}%> 

    <%= form.text_field :input, placeholder: "Input", class: "block w-full p-3 mb-4 border rounded border-grey-light", title:"input"%> 

  <div class="p-3 mb-5 border rounded ", title="environment">
    <%= form.label :environment_id, "Environment:", class: "text-gray-500"%>
    <%= form.select :environment_id, Environment.all.pluck(:name, :id), {}, {class: "bg-transparent float-right"} %>
  </div>

  <div class="p-3 mb-5 border rounded ", title="script">
    <%= form.label :scriptid, "Script:", class: "text-gray-500"%>
    <%= form.select :script_id, Script.all.pluck(:title, :id), {}, {class: "bg-transparent float-right"} %>
  </div>

  <hr class="my-5">

  <div class="flex justify-around actions">
    <%= form.submit class: "py-3 text-center mr-5 text-gray-100 bg-green-400 rounded w-full hover:bg-green-600 focus:outline-none"  %>
    <%= link_to 'Cancel', executions_path, class: "ml-5 px-4 py-3 text-center text-white bg-gray-600 rounded w-full hover:bg-gray-800" %>
  </div>
<% end %>

app/views/executions/edit.html.erb
<div class="flex flex-col min-h-screen bg-grey-lighter">
  <div class="container max-w-lg px-2 mx-auto">
    <div class="w-full px-6 py-8 text-black bg-white rounded shadow-md">
      <h1 class="mb-8 text-3xl text-center">Editing Execution</h1>

      <%= render 'form', execution: @execution %>

    </div>
  </div>
</div>

app/views/executions/index.html.erb
<div class="container max-w-6xl p-5 mx-auto bg-white shadow rounded-md">
  <h1 class="mb-8 text-3xl text-center">Executions</h1>

  <table class="w-full">
    <thead>
      <tr>
        <th>Requester</th>
        <th>State</th>
        <th>Started at</th>
        <th>Duration</th>
        <th>Script</th>
        <th>Environment</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @executions.each do |execution| %>
        <tr>
          <td><%= execution.user.email %></td>
          <td><%= execution.aasm_state %></td>
          <td title=<%= execution.started_at.to_s.split(' ').join('_') if execution.started_at.present? %>>
            <%= time_ago_in_words(execution.started_at) + ' ago' if execution.started_at.present? %>
          </td>
          <td title=<%= execution.duration.round.to_s + "_second".pluralize(execution.duration.round) if execution.duration.present?%>>
            <%= distance_of_time_in_words execution.duration if execution.duration.present? %>
          </td>
          <td><%= execution.script.title %></td>
          <td><%= execution.environment.name %></td>
          <td><%= link_to 'show', execution, class: "rounded px-2 text-gray-600 bg-gray-400 hover:bg-gray-300 cursor-pointer text-center" %></td>
          <td>
            <%= link_to "destroy", { action: "destroy", id: execution.id }, method: :delete, data: { confirm: "Are you sure?" }, class: "rounded px-2 text-red-400 hover:bg-gray-400 cursor-pointer bg-gray-400" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="float-right mx-5 my-2 overflow-auto text-gray-600">
    <%= paginate @executions %>
  </div>

  <hr class="mt-10 mb-5">

  <%= link_to 'New Execution', new_execution_path, class: "px-4 py-3 text-center text-white bg-green-400 rounded w-full hover:bg-green-600" %>
</div>

app/views/executions/new.html.erb
<div class="flex flex-col min-h-screen bg-grey-lighter">
  <div class="container max-w-lg px-2 mx-auto">
    <div class="w-full px-6 py-8 text-black bg-white rounded shadow-md">
      <h1 class="mb-8 text-3xl text-center">New Execution</h1>

      <%= render 'form', execution: @execution %>

    </div>
  </div>
</div>

app/views/executions/show.html.erb
<%= render @execution %>