config/routes.rb
Rails.application.routes.draw do
  get 'analytics/index'
  resources :executions do
    member do
      post 'action'
    end
  end
  resources :environments
  resources :scripts do
    member do
      post 'action'
    end
  end
 
  devise_for :users
  root 'home#index'
  get 'home/index'
end

app/models/environment.rb
class Environment < ApplicationRecord
  has_many :executions, dependent: :destroy
  validates :name, presence: true
  validates :private_key_path, presence: true
  validates :user_name, presence: true
  validates :fqdn, presence: true
end

app/controllers/environments_controller.rb
class EnvironmentsController < ApplicationController
  before_action :set_environment, only: [:show, :edit, :update, :destroy]

  # GET /environments
  # GET /environments.json
  def index
    authorize Environment
    @environments = Environment.order(started_at: :desc).page params[:page]
  end

  # GET /environments/1
  # GET /environments/1.json
  def show
  end

  # GET /environments/new
  def new
    @environment = Environment.new
  end

  # GET /environments/1/edit
  def edit
  end

  # POST /environments
  # POST /environments.json
  def create
    @environment = Environment.new(environment_params)

    respond_to do |format|
      if @environment.save
        format.html { redirect_to @environment, notice: 'Environment was successfully created.' }
        format.json { render :show, status: :created, location: @environment }
      else
        format.html { render :new }
        format.json { render json: @environment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /environments/1
  # PATCH/PUT /environments/1.json
  def update
    respond_to do |format|
      if @environment.update(environment_params)
        format.html { redirect_to @environment, notice: 'Environment was successfully updated.' }
        format.json { render :show, status: :ok, location: @environment }
      else
        format.html { render :edit }
        format.json { render json: @environment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /environments/1
  # DELETE /environments/1.json
  def destroy
    @environment.destroy
    respond_to do |format|
      format.html { redirect_to environments_url, notice: 'Environment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_environment
      @environment = Environment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def environment_params
      params.require(:environment).permit(:name, :private_key_path, :fqdn, :user_name)
    end
end

app/helpers/environments_helper.rb
module EnvironmentsHelper
end

app/views/environments/_form.html.erb
<%= form_with(model: environment, local: true) do |form| %>
  <% if environment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(environment.errors.count, "error") %> prohibited this environment from being saved:</h2>

      <ul>
        <% environment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div data-controller="sshconnection">
    <%= form.text_field :user_name, placeholder: "Username", class: "block w-full p-3 mb-4 border rounded border-grey-light", 'data-target': 'sshconnection.user_name', 'data-action':"sshconnection#evalstring", title:"user name" %>

    <%= form.text_field :fqdn, placeholder: "FQDN", class: "block w-full p-3 mb-4 border rounded border-grey-light", 'data-target': 'sshconnection.fqdn', 'data-action':"sshconnection#evalstring", title:"FQDN" %>

    <%= form.text_field :private_key_path, placeholder: "Private Key Path", class: "block w-full p-3 mb-4 border rounded border-grey-light", 'data-target': 'sshconnection.key', 'data-action':"sshconnection#evalstring", title:"private ssh key path" %>

    <%= form.text_field :name, placeholder: "Environment Name", class: "block w-full p-3 mb-4 border rounded border-grey-light", 'data-target': 'sshconnection.name', 'data-action':"sshconnection#evalstring", title:"environment name"  %>

    <div class="w-full p-3 text-gray-300 bg-gray-800 rounded", title="ssh connection string" >
      <span class="text-green-400">prometheus</span>@<span class="text-blue-400">server</span> ~ $ <span data-target="sshconnection.connection"></span>
    </div>
  </div>

  <hr class="my-5">

  <div class="flex justify-around actions">
    <%= form.submit class: "py-3 text-center mr-5 text-gray-100 bg-green-400 rounded w-full hover:bg-green-600 focus:outline-none"  %>
    <%= link_to 'Cancel', environments_path, class: "ml-5 px-4 py-3 text-center text-white bg-gray-600 rounded w-full hover:bg-gray-800" %>
  </div>
<% end %>

app/views/environments/edit.html.erb
<div class="flex flex-col bg-grey-lighter">
  <div class="container w-full px-2 mx-auto lg:w-1/2">
    <div class="w-full px-6 py-8 text-black bg-white rounded shadow-md">
      <h1 class="mb-8 text-3xl text-center"> Editing Environment</h1>

      <%= render 'form', environment: @environment %>

    </div>
  </div>
</div>

app/views/environments/index.html.erb
<div class="container max-w-5xl p-5 mx-auto bg-white shadow rounded-md">
  <h1 class="mb-8 text-3xl text-center">Environments</h1>

  <table class="w-full">
    <thead>
      <tr>
        <th>Name</th>
        <th>Private key path</th>
        <th>FQDN</th>
        <th>User name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @environments.each do |environment| %>
        <tr>
          <td><%= environment.name %></td>
          <td><%= environment.private_key_path %></td>
          <td><%= environment.fqdn %></td>
          <td><%= environment.user_name %></td>
          <td><%= link_to 'show', environment, class: "rounded px-2 text-gray-800 hover:bg-gray-400 cursor-pointer bg-gray-400"   %></td>
          <td><%= link_to 'edit', edit_environment_path(environment), class: "rounded px-2 text-gray-800 hover:bg-gray-400 cursor-pointer bg-gray-400"   %></td>
          <td><%= link_to 'destroy', environment, method: :delete, data: { confirm: 'Are you sure?' }, class: "rounded px-2 text-red-400 hover:bg-gray-400 cursor-pointer bg-gray-400"   %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="float-right mx-5 my-2 overflow-auto text-gray-600">
    <%= paginate @environments%>
  </div>

  <hr class="my-5">

  <%= link_to 'New Environment', new_environment_path, class: "px-4 py-3 text-center text-white bg-green-400 rounded w-full hover:bg-green-600" %>
</div>

app/views/environments/new.html.erb
<div class="flex flex-col bg-grey-lighter">
  <div class="container w-full px-2 mx-auto lg:w-1/2">
    <div class="w-full px-6 py-8 text-black bg-white rounded shadow-md">
      <h1 class="mb-8 text-3xl text-center">New Environment</h1>

      <%= render 'form', environment: @environment %>

    </div>
  </div>
</div>

app/views/environments/show.html.erb
<div class="flex flex-col bg-grey-lighter">
  <div class="container w-full px-2 mx-auto lg:w-1/2">
    <div class="w-full px-6 py-8 text-black bg-white rounded shadow-md">
      <h1 class="mb-8 text-3xl text-center"><%= @environment.name.titleize %> Environment</h1>

      <%= form_with(model: @environment, local: true) do |form| %>
        <div data-controller="sshconnection">
          <%= form.text_field :user_name, placeholder: "Username", class: "block w-full p-3 mb-4 border rounded border-grey-light", 'data-target': 'sshconnection.user_name', 'data-action':"sshconnection#evalstring", disabled: true, title:"user name"%>

          <%= form.text_field :fqdn, placeholder: "FQDN", class: "block w-full p-3 mb-4 border rounded border-grey-light", 'data-target': 'sshconnection.fqdn', 'data-action':"sshconnection#evalstring", disabled: true, title:"FQDN" %>

          <%= form.text_field :private_key_path, placeholder: "Private Key Path", class: "block w-full p-3 mb-4 border rounded border-grey-light", 'data-target': 'sshconnection.key', 'data-action':"sshconnection#evalstring", disabled: true, title:"private ssh key path"  %>

          <%= form.text_field :name, placeholder: "Environment Name", class: "block w-full p-3 mb-4 border rounded border-grey-light", 'data-target': 'sshconnection.name', 'data-action':"sshconnection#evalstring", title:"environment name", disabled: true  %>

          <div class="w-full p-3 text-gray-300 bg-gray-800 rounded", title="ssh connection string" >
            <span class="text-green-400">prometheus</span>@<span class="text-blue-400">server</span> ~ $ <span data-target="sshconnection.connection"></span>
          </div>
        </div>
      <% end %>

      <hr class="my-5">

      <%= link_to 'Back', environments_path, class: "px-4 py-3 text-center text-white bg-gray-600 rounded w-full hover:bg-gray-800" %>
    </div>
  </div>
</div>