config/routes.rb
Rails.application.routes.draw do
  get 'analytics/index'
  resources :executions do
    member do
      post 'action'
    end
  end
  resources :environments
  resources :scripts do
    member do
      post 'action'
    end
  end
 
  devise_for :users
  root 'home#index'
  get 'home/index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prometheus</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="mb-12 overflow-auto text-white bg-gray-600 shadow-md">
      <ul class="flex float-left py-5 ml-5 space-x-10">
        <li class="hover:text-green-400"><%= link_to("Home", root_path) %></li>
        <% if policy(Environment).index? %>
          <li class="hover:text-green-400"><%= link_to("Environments", environments_path) %></li>
        <% end %>
        <% if policy(Script).index? %>
          <li class="hover:text-green-400"><%= link_to("Scripts", scripts_path) %></li>
        <% end %>
        <% if policy(Execution).index? %>
          <li class="hover:text-green-400"><%= link_to("Executions", executions_path) %></li>
        <% end %>
        <% if policy(Execution).index? %>
          <li class="hover:text-green-400"><%= link_to("Analytics", analytics_index_path) %></li>
        <% end %>
      </ul>
      <ul class="flex float-right py-5 mr-5 space-x-10">
        <% if user_signed_in? %>
        <li>
          <%= current_user.email %>        
          <%= if role = current_user.active_roles.first.presence then role.capitalize.to_s.prepend(" | ") else "" end %>
        </li>
        <li class="hover:text-green-400">
          <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
        </li>
        <% else %>
        <li class="hover:text-green-400">
          <%= link_to "Sign up", new_registration_path(User) %><br />
        </li>
        <li class="hover:text-green-400">
          <%= link_to('Login', new_user_session_path) %>  
        </li>
        <% end %>
      </ul>
      <% flash.each do |message_type, message| %>
        <div data-controller="hide" data-target="hide.self" class="text-center clear-both <%= message_type == 'alert' ? 'bg-red-400' : 'bg-green-400' %> text-gray-100 absolute mt-16 w-full">
          <%= message %>
        </div>
      <% end %>
    </nav>

    <%= yield %>

  </body>
</html>